import type { Metadata } from 'next'
import { Playfair_Display } from 'next/font/google'
import './globals.css'
import CssBaseline from '@mui/material/CssBaseline';
import StyleWrapper from '@/app-layouts/wrappers/style-wrapper';
import WholeWrapper from '@/app-layouts/wrappers/whole-wrapper';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import ReduxWrapper from "@/redux/wrapper";
import 'keen-slider/keen-slider.min.css'


const inter = Playfair_Display({
  subsets: ['latin'],
  // weight: ['100', '300', '400', '500', '700', '900'],
  // weight: ['200', '300', '400', '500','600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ReduxWrapper>
            <StyleWrapper>
              <CssBaseline enableColorScheme />
              <WholeWrapper>
                {children}
              </WholeWrapper>
            </StyleWrapper>
          </ReduxWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
